### ISSUE TITLE
This does not actually produce Title Case text

### ISSUE THREAD

**Issue by mansona** [blakeembrey/title-case#11]
Hi folks 👋 

I'm just looking for something that can produce title-case text for me and I came across this as the most popular npm package to do the job.

But looking at your documentation it seems like you are not actually creating title case text 🤔 What I was expecting to see was what is defined here: [https://en.wikipedia.org/wiki/Letter_case#Title_Case](https://en.wikipedia.org/wiki/Letter_case#Title_Case). Am I missing an un-documented setting or something?

I will try to create a failing test at some point today that communicates what I'm trying to say.

**Comment by blakeembrey** [comment]
See https://github.com/blakeembrey/title-case/pull/12#issuecomment-377909941. Unfortunately this just isn't very well named. The package is available to anyone who wants to implement proper title case, I just haven't had time to unpublish it myself and notify any dependencies.

**Comment by blakeembrey** [comment]
I'll reopen to remind myself, or anyone else, to actually implement this in the next major version (hopefully I'll find time in the next few months to pull it off). FWIW, this module be renamed and the new functionality can replace this one.

**Comment by blakeembrey** [comment]
This has been changed/fixed in the current major release of `title-case`.
