### ISSUE TITLE
How do I change the delimiter character in this library?

### ISSUE THREAD

**Issue by laodemalfatih** [blakeembrey/title-case#16]
The "title_case" function uses pseudo foreign characters as delimiter. How do I change the delimiter character in this library?

**My Expectations**

`hello_world` => `Hello_world`
`hello*world` => `Hello*world`

**Reality**

`hello_world` => `Hello_World`
`hello*world` => `Hello*World`

Can I prevent this library from using certain characters as delimiters?

**Comment by blakeembrey** [comment]
I've added some documentation for the latest major release on how to alter these behaviors in https://github.com/blakeembrey/change-case/tree/master/packages/no-case#options.
