### ISSUE TITLE
Changing case removes punctuation

### ISSUE THREAD

**Issue by mikemaccana** [blakeembrey/title-case#4]
title-case 1.1.0 removes punctuation, eg:

    > changeCase.titleCase('hello world A.B.C')
    'Hello World A B C'
    > changeCase.titleCase('steve & jan')
    'Steve Jan'

**Comment by blakeembrey** [comment]
Hi @mikemaccana! This is an unfortunate naming/documentation issue. Proper title casing is a lot more complicated (this is mostly for converting between different cases in automatically generated situations). Have a look at https://github.com/blakeembrey/title-case/issues/3. I'll try to get around to improving the docs in the next week or so.
